---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: until [[ -f /var/lib/cloud/instance/boot-finished ]]; do sleep 1; done && test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal python-zipstream)
      args:
        executable: /bin/bash
      become: true
      changed_when: false

- name: run the main role
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - role: entercloudsuite.filesystem
      disk_additional_disks:
        - disk: /dev/vdb
          fstype: xfs
          mount_options: defaults
          mount: "/var/ncdata"
          disable_periodic_fsck: false
- name: mysql disk
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - role: entercloudsuite.filesystem
      disk_additional_disks:
        - disk: /dev/vdc
          fstype: xfs
          mount_options: defaults
          mount: "/var/lib/mysql"
          disable_periodic_fsck: false

